version: '2'

services:
  dashboard:
    build: ./dashboard
    volumes:
      - ./dashboard:/usr/src/dashboard
    ports:
      - '4200:4200'
      - '35730:35730'
    command: 'ember s'
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/api
    ports:
      - '3000:3000'
    command: 'yarn start'
  kiosk:
    build: ./ki-os
    ports: 
      - '8080:8080'
      - '9090:9090'
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/input:/dev/input"
      - "/dev/snd:/dev/snd"
      - "/dev/video0:/dev/video0"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/etc/localtime:/etc/localtime:ro"
      - "$HOME/.config/app:/root/.config/app"
      - ./ki-os:/app
      - /app/node_modules
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    privileged: true
    restart: always
    command: bash -c "yarn && yarn start:electron"
  postgres:
    image: postgres:9.6.2
    environment:
      POSTGRES_DB: 'nboi_production'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'strict.bases.prospect.affluent.mephitic'
    ports:
      - '5432:5432'
